# Generated by Django 3.1.2 on 2020-11-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_followlist_likes_posts_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
