# Generated by Django 3.1.1 on 2020-10-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_bid',
            new_name='current_bid',
        ),
    ]
