# Generated by Django 3.1.1 on 2020-10-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201004_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='current_bid',
        ),
    ]
