# Generated by Django 3.1.1 on 2020-10-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_watchlist_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='activity',
            field=models.CharField(default='open', max_length=10),
            preserve_default=False,
        ),
    ]
