# Generated by Django 3.1.1 on 2020-10-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
