# Generated by Django 3.1.2 on 2020-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeon', '0003_announcement_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
