# Generated by Django 3.1.2 on 2020-11-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeon', '0004_auto_20201126_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='description',
            new_name='body',
        ),
    ]
