# Generated by Django 3.1.2 on 2020-11-28 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odeon', '0006_auto_20201128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Role',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
