# Generated by Django 3.1.2 on 2020-11-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odeon', '0007_announcement_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='Role',
            new_name='role',
        ),
    ]
