# Generated by Django 3.1.3 on 2020-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeon', '0009_auto_20201128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
